# Generated by Django 4.2.6 on 2024-05-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_reg', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SendOtp',
        ),
        migrations.AlterField(
            model_name='otpverifiaction',
            name='date',
            field=models.CharField(default='2024-05-09', max_length=10),
        ),
        migrations.AlterField(
            model_name='phoneuser',
            name='date',
            field=models.CharField(default='2024-05-09', max_length=10),
        ),
        migrations.DeleteModel(
            name='UserSendOtp',
        ),
    ]
