# Generated by Django 4.2.6 on 2024-09-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_reg', '0002_delete_sendotp_alter_otpverifiaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverifiaction',
            name='date',
            field=models.CharField(default='2024-09-13', max_length=10),
        ),
        migrations.AlterField(
            model_name='phoneuser',
            name='date',
            field=models.CharField(default='2024-09-13', max_length=10),
        ),
    ]
