# Generated by Django 4.2.6 on 2024-05-08 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matrimony_crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompatibilityMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('How_often_do_you_go_out', models.CharField(blank=True, max_length=222, null=True)),
                ('How_would_you_describe_your_clothes', models.CharField(blank=True, max_length=235, null=True)),
                ('How_do_you_spend_your_free_time', models.CharField(blank=True, max_length=235, null=True)),
                ('How_many_times_do_you_visit_salon_or_beauty_parlour', models.CharField(blank=True, max_length=235, null=True)),
                ('How_many_times_do_you_go_out_drinking_or_in_a_pub', models.CharField(blank=True, max_length=235, null=True)),
                ('What_would_you_choose_for_a_romantic_date_with_your_partner', models.CharField(blank=True, max_length=234, null=True)),
                ('Which_social_platform_do_you_use_Most', models.CharField(blank=True, max_length=234, null=True)),
                ('Do_you_like_shopping', models.BooleanField(blank=True, null=True)),
                ('Preferences_while_traveling', models.CharField(blank=True, max_length=234, null=True)),
                ('Which_personality_are_you', models.CharField(blank=True, max_length=234, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
