# Generated by Django 4.2.6 on 2024-05-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_crud', '0002_usercompatibilitymatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompatibilitymatch',
            name='created_at',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
    ]
