# Generated by Django 4.2.6 on 2024-05-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MutualProfile', '0005_alter_userprofilemutual_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemutual',
            name='created_at',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
