# Generated by Django 4.2.6 on 2024-04-24 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educationdetails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationdetail',
            old_name='qualification',
            new_name='qualifications',
        ),
    ]
