# Generated by Django 4.2.6 on 2024-04-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educationdetails', '0002_rename_qualification_educationdetail_qualifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationdetail',
            old_name='occupation',
            new_name='occupations',
        ),
        migrations.RenameField(
            model_name='educationdetail',
            old_name='qualifications',
            new_name='qualification',
        ),
    ]
