# Generated by Django 4.2.6 on 2024-04-23 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCompletionsApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_information', models.IntegerField(blank=True, null=True)),
                ('profile_photo', models.IntegerField(blank=True, null=True)),
                ('education_details', models.IntegerField(blank=True, null=True)),
                ('horoscope_details', models.IntegerField(blank=True, null=True)),
                ('partner_prefrence', models.IntegerField(blank=True, null=True)),
                ('family_details', models.IntegerField(blank=True, null=True)),
                ('habits', models.IntegerField(blank=True, null=True)),
                ('hobbies', models.IntegerField(blank=True, null=True)),
                ('interest', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='uploads/')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=25, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, choices=[('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Chhattisgarh', 'Chhattisgarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharastra', 'Maharastra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Puducherry', 'Puducherry'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telengana', 'Telengana'), ('Tripura', 'Tripura'), ('Uttarkhand', 'Uttarkhand'), ('Uttar Pradesh', 'Uttar Pradesh'), ('West Bengal', 'West Bengal')], max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=6, null=True)),
                ('date', models.CharField(blank=True, default='2024-04-23', max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, default=None, null=True)),
                ('gender', models.CharField(blank=True, default=None, max_length=222222222, null=True)),
                ('religion', models.CharField(blank=True, default=None, max_length=222222222, null=True)),
                ('caste', models.CharField(blank=True, default=None, max_length=222222222, null=True)),
                ('height', models.CharField(blank=True, default=None, max_length=222222222, null=True)),
                ('education', models.CharField(blank=True, default=None, max_length=222222222, null=True)),
                ('occupation', models.CharField(blank=True, default=None, max_length=222222222, null=True)),
                ('income', models.IntegerField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
