# Generated by Django 4.2.6 on 2024-04-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.CharField(blank=True, default='2024-04-24', max_length=10, null=True),
        ),
    ]
