# Generated by Django 4.2.6 on 2024-05-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapi', '0005_alter_profile_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.CharField(blank=True, default='2024-05-06', max_length=10, null=True),
        ),
    ]
